- name: mac os | install brews formulas
  homebrew:
    name:
      - atool
      - fzf
      - git
      - git-flow
      - gzip
      - htop
      - jq
      - lazygit
      - lf
      - ncdu
      - neovim
      - p7zip
      - ripgrep
      - unar
      - unzip
      - yt-dlp
      - zip
      - zsh
    state: latest

- name: mac os | install brew casks
  command: "brew install --cask {{ item }}"
  with_items:
      - alacritty
      - appcleaner
      - brave-browser
      - firefox
      - mpv
      - onyx
      - the-unarchiver
      - transmission
  ignore_errors: true
