---
- name: mac os | Aerospace
  block:
    - name: mac os | aerospace | install cask
      ansible.builtin.command: "brew install --cask {{ item }}"
      with_items:
        - nikitabobko/tap/aerospace
      ignore_errors: true

    - name: mac os | aerospace | create conf directory
      ansible.builtin.file:
        path: "$HOME/.config/aerospace"
        state: directory

    - name: mac os | aerospace | copy configuration
      ansible.builtin.copy:
        src: packages/aerospace-config.toml
        dest: "$HOME/.config/aerospace/aerospace.toml"
