---
- name: mac os | Aerospace
  block:
    - name: mac os | aerospace | install cask
      ansible.builtin.command: "brew install --cask {{ item }}"
      with_items:
        - nikitabobko/tap/aerospace
      ignore_errors: true
