---
- name: mac os | Install taps
  ansible.builtin.command: "brew tap {{ item }}"
  with_items:
    - "CJ-Systems/homebrew-gitflow-cjs"
  ignore_errors: true

- name: mac os | Install brews formulas
  community.general.homebrew:
    name:
      - atool
      - fzf
      - git
      - gzip
      - htop
      - jq
      - lazygit
      - lf
      - ncdu
      - git-flow-cjs
      - neovim
      - p7zip
      - ripgrep
      - unar
      - unzip
      - yt-dlp
      - zip
      - zsh
    state: latest

- name: mac os | Install brew casks
  ansible.builtin.command: "brew install --cask {{ item }}"
  with_items:
    - appcleaner
    - brave-browser
    - firefox
    - ghostty
    - mpv
    - onyx
    - the-unarchiver
    - transmission
  ignore_errors: true
