- name: system setup | dotfiles | Linux
  become_user: ale
  block:
    - name: system setup | dotfiles | Clone repo
      git:
        bare: yes
        repo: https://github.com/dixiedream/dotfiles.git
        dest: "{{ dotfile_src }}"

    - name: system setup | dotfiles | Setup repo
      command: "git --git-dir={{ dotfile_src }} --work-tree='{{ user_home }}' checkout -f master"

    - name: system setup | dotfiles | Setup repo
      command: "git --git-dir={{ dotfile_src }} --work-tree='{{ user_home }}' config --local status.showUntrackedFiles no"

    - name: system setup | dotfiles | Setup repo
      command: "git --git-dir={{ dotfile_src }} --work-tree='{{ user_home }}' config remote.origin.url 'git@github.com:dixiedream/dotfiles.git'"

    - name: system setup | dotfiles | Setup repo
      command: "git --git-dir={{ dotfile_src }} --work-tree='{{ user_home }}' config remote.origin.fetch 'refs/heads/*:refs/remotes/origin/*'"

    # - name: system setup | dotfiles | Check file permissions
    #   file:
    #     path: '/home/ale'
    #     recurse: yes
    #     state: directory
    #     owner: ale
    #     group: ale
  when: ansible_system == "Linux"
