# We're unable to know the name of the different outputs
# for different machines so we're basically creating
# a template... [AL20231128]
---
- name: system setup | kanshi
  become_user: "{{ user }}"
  when: wayland_install_type is not defined or wayland_install_type == 'wm'
  block:
    - name: system setup | kanshi | create config template
      blockinfile:
        path: "/home/{{ user }}/.config/kanshi/config"
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        block: |
          # Example configuration:
          #   output HDMI-A-1 resolution 1920x1080 position 1920,0
          # You can get the names of your outputs by running: hyprctl monitors all
          #profile dock {
          #  output LVDS-1 disable
          #  output HDMI-A-1 enable position 0,0
          #}
          #
          #profile laptop {
          #  output LVDS-1 enable position 0,0
          #}




