- name: system setup | remove beep | remove pcspkr
  become: true
  command: rmmod pcspkr
  ignore_errors: yes

- name: system setup | remove beep | check if already blacklisted
  become: true
  stat:
    path: /etc/modprobe.d/nobeep.conf
  register: nobeep_check

- name: system setup | remove beep | blacklist pcspkr
  become: true
  shell: echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
  when: not nobeep_check.stat.exists
