# Print server
- name: CUPS | Archlinux
  become: true
  block:
    - name: CUPS | install needed packages
      pacman:
        name:
          - cups
          - system-config-printer
        state: latest

    - name: CUPS | ensure service is not enabled
      service:
        name: cups.service
        state: stopped
        enabled: no

    - name: CUPS | ensure socket is enabled
      service:
        name: cups.socket
        state: started
        enabled: yes
  when: ansible_distribution in ["Archlinux", "Artix Linux"]

# Printers specific stuff
- name: Canon MG3650 | Archlinux
  become_user: "{{ user }}"
  shell: yay -S --noconfirm --removemake cnijfilter2-mg3600
  when: ansible_distribution in ["Archlinux", "Artix Linux"]
