---
# Print server
- name: CUPS | Archlinux
  become: true
  when: ansible_distribution in ["Archlinux", "Artix Linux"]

  # Printers specific stuff
  block:
    - name: CUPS | install needed packages
      community.general.pacman:
        name:
          - cups
          - ghostscript
          - system-config-printer
        state: latest

    - name: CUPS | ensure service is not enabled
      ansible.builtin.service:
        name: cups.service
        state: stopped
        enabled: false

    - name: CUPS | ensure socket is enabled
      ansible.builtin.service:
        name: cups.socket
        state: started
        enabled: true
