---
- hosts: all
  pre_tasks:
    - name: pre-run | update package cache (Archlinux)
      become: true
      pacman:
        update_cache: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian)
      become: true
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_os_family == "Debian"

    - name: pre-run | update package cache (MacOS)
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      changed_when: false
      when: ansible_os_family == "Darwin"

  # run roles
- hosts: all
  roles:
    - base
    - dev

- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian)
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_os_family == "Debian"

  - name: autoremove orphan packages (debian)
    apt:
      autoremove: yes
      purge: yes
    when: ansible_os_family == "Debian"
