---
- hosts: all
  pre_tasks:
    - name: pre-run | Update package cache (Pacman)
      become: true
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: pre-run | Update package cache (Apt)
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family == "Debian"

# run roles
- hosts: all
  vars:
    dotfiles_branch: "master"
  roles:
    - dev

- hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (Apt)
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Autoremove orphan packages (Apt)
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_os_family == "Debian"
