---
- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      pacman: update_cache=yes
      changed_when: False

  # run roles
- hosts: all
  connection: local
  become: true
  roles:
    - base

# - hosts: dev
#   become: true
#   roles:
#     - dev

# - hosts: server
#   tags: server
#   become: true
#   roles:
#     - server
#
