---
- hosts: all
  pre_tasks:
    - name: pre-run | Update package cache (MacOS)
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      changed_when: false
      when: ansible_os_family == "Darwin"

# run roles
- hosts: all
  roles:
    - mac
