---
- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | update package cache (MacOS)
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      changed_when: false
      when: ansible_os_family == "Darwin"

  # run roles
- hosts: all
  roles:
    - mac
