---
- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | Update package cache (Pacman)
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: pre-run | Update package cache (Apt)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family in "Debian"

# run roles
- hosts: all
  roles:
    - pro_audio

- hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (Apt)
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_os_family in "Debian"

    - name: Autoremove orphan packages (Apt)
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_os_family in "Debian"
