---
- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | Update package cache (Pacman)
      community.general.pacman:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: pre-run | Update package cache (Apt)
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS"]

# run roles
- hosts: all
  vars:
    dotfiles_branch: "feature/wayland"
  roles:
    - base
    - wayland

- hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (Apt)
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS"]

    - name: Autoremove orphan packages (Apt)
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_distribution in ["Debian", "Pop!_OS"]
