---
- name: system setup | address book | enable the debug menu
  community.general.osx_defaults:
    domain: com.apple.addressbook
    key: ABShowDebugMenu
    type: bool
    value: true

- name: system setup | address book | enable the debug menu in iCal (pre-10.8)
  community.general.osx_defaults:
    domain: com.apple.iCal
    key: IncludeDebugMenu
    type: bool
    value: true

- name: system setup | address book | restart
  ansible.builtin.command: killall Address Book
  changed_when: false
  ignore_errors: true
