---
- name: software | chrome | disable the all too sensitive backswipe on trackpads
  community.general.osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false

- name: software | chrome | disable the all too sensitive backswipe on Magic Mouse
  community.general.osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableMouseSwipeNavigateWithScrolls
    type: bool
    value: false

- name: software | chrome | use the system-native print preview dialog
  community.general.osx_defaults:
    domain: com.google.Chrome
    key: DisablePrintPreview
    type: bool
    value: true

- name: software | chrome | expand the print dialog by default
  community.general.osx_defaults:
    domain: com.google.Chrome
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true

- name: software | chrome | restart
  ansible.builtin.command: killall Google Chrome
  changed_when: false
  ignore_errors: true
