---
# - name: system setup | finder | - name: system setup | finder | enable quitting
#   osx_defaults:
#     domain: com.apple.finder
#     key: QuitMenuitem
#     type: bool
#     value: true

- name: system setup | finder | disable window animations
  community.general.osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

- name: system setup | finder | show icons for external hard drives
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: system setup | finder | show icons for hard drives
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

- name: system setup | finder | show servers icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

- name: system setup | finder | show removable media icons
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

- name: system setup | finder | hide recent tags on sidebar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: bool
    value: false

- name: system setup | finder | hide hidden files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: false

- name: system setup | finder | show file name extension
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: system setup | finder | hide status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: false

- name: system setup | finder | hide path bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: false

- name: system setup | finder | show full POSIX path as window title
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: system setup | finder | keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true

- name: system setup | finder | search the current folder first
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

- name: system setup | finder | disable the warning when changing a file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: system setup | finder | enable spring loading for directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true

- name: system setup | finder | remove the spring loading delay for directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0

- name: system setup | finder | avoid creating .DS_Store files on network
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: system setup | finder | avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: system setup | finder | Disable disk image verification
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify
    type: bool
    value: true

- name: system setup | finder | Disable disk image verification 2
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-locked
    type: bool
    value: true

- name: system setup | finder | Disable disk image verification 3
  community.general.osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-remote
    type: bool
    value: true

- name: system setup | finder | Use list view in all windows by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

- name: system setup | finder | Disable the warning before emptying the Trash
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: system setup | finder | Enable AirDrop over Ethernet and on unsupported Macs running Lion
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true

# - name: system setup | finder | Show the ~/Library folder
#   shell: chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library

- name: system setup | finder | Show the /Volumes folder
  become: true
  ansible.builtin.command: chflags nohidden /Volumes
- name: system setup | finder | Expand the following File Info panes
  ansible.builtin.command: "defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true"
- name: system setup | finder | restart
  ansible.builtin.command: killall Finder
  changed_when: false
  ignore_errors: true
