---
- name: system setup | messages | Disable automatic emoji substitution (i.e. use plain text smileys)
  ansible.builtin.command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool
    false
- name: system setup | messages | Disable smart quotes as it’s annoying for messages that contain code
  ansible.builtin.command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false
- name: system setup | messages | Disable continuous spell checking
  ansible.builtin.command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false
- name: system setup | messages | restart
  ansible.builtin.command: killall Messages
  changed_when: false
  ignore_errors: true
