- name: system setup | messages | Disable automatic emoji substitution (i.e. use plain text smileys)
  command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

- name: system setup | messages | Disable smart quotes as it’s annoying for messages that contain code
  command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

- name: system setup | messages | Disable continuous spell checking
  command: defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

- name: system setup | messages | restart
  shell: killall Messages
  changed_when: false
  ignore_errors: true
