---
- name: system setup | photos | Prevent from opening automatically when devices are plugged in
  community.general.osx_defaults:
    host: currentHost
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: true

- name: system setup | photos | restart
  ansible.builtin.command: killall Photos
  changed_when: false
  ignore_errors: true
