---
- name: system setup | Enable lid wakeup
  become: true
  ansible.builtin.command: pmset -a lidwake 1
- name: system setup | Sleep the display after 15 minutes
  become: true
  ansible.builtin.command: pmset -a displaysleep 15
- name: system setup | Disable machine sleep while charging
  become: true
  ansible.builtin.command: pmset -c sleep 0
- name: system setup | Set machine sleep to 5 minutes on battery
  become: true
  ansible.builtin.command: pmset -b sleep 5
- name: system setup | Disable hibernation
  become: true
  ansible.builtin.command: pmset -a hibernatemode 0
- name: system setup | Remove sleep image file
  become: true
  ansible.builtin.command: rm /private/var/vm/sleepimage
  ignore_errors: true

- name: system setup | Create 0 byte file instead
  become: true
  ansible.builtin.command: touch /private/var/vm/sleepimage
  args:
    creates: /private/var/vm/sleepimage

- name: system setup | Setup permission for sleepimage
  become: true
  ansible.builtin.command: chflags uchg /private/var/vm/sleepimage
