---
- name: system setup | Tap to click step 1
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true

- name: system setup | Tap to click step 2
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: true

- name: system setup | tap to click | step 3
  community.general.osx_defaults:
    domain: com.apple.driver.AppleMultitouch.trackpad
    key: Clicking
    type: bool
    value: true
  become: true

- name: system setup | tap to click | step 4
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
    host: currentHost

- name: system setup | tap to click | step 5
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- name: system setup | Disable natural scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
