- name: system setup | text edit | Use plain text mode for new documents
  osx_defaults:
    domain: com.apple.TextEdit 
    key: RichText 
    type: int 
    value: 0

- name: system setup | text edit | Open files as UTF-8
  osx_defaults:
    domain: com.apple.TextEdit 
    key: PlainTextEncoding 
    type: int 
    value: 4

- name: system setup | text edit | Save files as UTF-8
  osx_defaults:
    domain: com.apple.TextEdit 
    key: PlainTextEncodingForWrite 
    type: int 
    value: 4
