---
- name: software | transmission | use `~/Downloads` to store completed downloads
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: DownloadLocationConstant
    type: bool
    value: true

- name: software | transmission | don’t prompt for confirmation before removing non-downloading active transfers
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: CheckRemoveDownloading
    type: bool
    value: true

- name: software | transmission | trash original torrent files
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: DeleteOriginalTorrent
    type: bool
    value: true

- name: software | transmission | hide the donate message
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: WarningDonate
    type: bool
    value: false

- name: software | transmission | hide the legal disclaimer
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: WarningLegal
    type: bool
    value: false

- name: software | transmission | randomize port on launch
  community.general.osx_defaults:
    domain: org.m0k.transmission
    key: RandomPort
    type: bool
    value: true

- name: software | transmission | restart
  ansible.builtin.command: killall Transmission
  changed_when: false
  ignore_errors: true
