- name: packages | golang | install  package (Archlinux)
  become: true
  pacman:
    name: go
    state: latest
  when: ansible_os_family in ["Archlinux", "Artix Linux"]

- name: packages | golang | download archive (Debian)
  become: true
  get_url:
    checksum: "{{ golang_checksum }}"
    url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: /tmp/golang.tar.gz
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | golang | extract archive (Debian)
  become: true
  unarchive:
    src: /tmp/golang.tar.gz
    dest: /usr/local/
    owner: root
    group: root
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | golang | update $PATH var (Debian)
  become_user: "{{ user }}"
  lineinfile:
    dest: "/home/{{ user }}/.zprofile"
    regexp: '^export PATH=\$PATH:\$GOROOT/bin:\$GOPATH/bin'
    line: "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin"
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | golang | install (MacOS)
  homebrew:
    name: go
    state: latest
  when: ansible_os_family == "Darwin"
