- name: packages | golang | install  package (Archlinux)
  pacman:
    name: go
    state: latest
  when: ansible_os_family == "Archlinux"

- name: packages | golang | download archive (Debian)
  get_url:
    checksum: "{{ golang_checksum }}"
    url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: /tmp/golang.tar.gz
  when: ansible_os_family == "Debian"

- name: packages | golang | creates dir if not exists (Debian)
  file:
    path: /usr/local/go
    state: directory
  when: ansible_os_family == "Debian"

- name: packages | golang | extract archive (Debian)
  unarchive:
    src: /tmp/golang.tar.gz
    dest: /usr/local
    owner: root
    group: root
  when: ansible_os_family == "Debian"

- name: packages | golang | update $PATH var (Debian)
  become_user: ale
  lineinfile:
    dest: "{{ user_home }}/.zprofile"
    regexp: '^export PATH=\$PATH:\$GOROOT/bin:\$GOPATH/bin'
    line: "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin"
  when: ansible_os_family == "Debian"
