---
- name: packages | Qemu
  become: true
  block:
    - name: packages | qemu | install required packages (Archlinux)
      community.general.pacman:
        name:
          - qemu-base
          # - dnsmasq
          - libvirt
          - virt-install
          - virt-manager
          - virt-viewer
          - edk2-ovmf
          - swtpm
        state: present
      when: ansible_os_family in ["Archlinux", "Artix Linux"]

    - name: packages | qemu | install required packages (Debian)
      ansible.builtin.apt:
        name:
          - qemu-system-x86
          - libvirt-daemon-system
          - virtinst
          - virt-manager
          - virt-viewer
          - qemu-utils
          - ovmf
          - swtpm
        state: present
      when: ansible_os_family in ["Debian"]

    - name: packages | qemu | ensure qemu related services are not enabled (Debian)
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - libvirtd
        - libvirt-guests
        - systemd-machined
        # - dnsmasq
      when: ansible_os_family in ["Debian"]

    - name: "users | {{ user }} | ensure {{ user }} is in libvirt group (Linux)"
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: libvirt
        append: true
      when: ansible_system == "Linux"

    - name: "users | {{ user }} | ensure {{ user }} is in kvm group (Ubuntu)"
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: kvm
        append: true
      when: ansible_distribution in ["Ubuntu"]
