---
- name: packages | Docker
  block:
    - name: packages | Install required packages (Linux)
      become: true
      ansible.builtin.package:
        name:
          - docker
          - docker-compose
        state: latest
      when: ansible_distribution in ["Artix Linux", "Archlinux", "Debian"]

    - name: packages | Enable Docker buildx (ArchLinux)
      when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

      block:
        - name: Docker | Install dependencies
          become: true
          ansible.builtin.package:
            name:
              - curl
              - ca-certificates
            state: present

        - name: Docker | check executable
          ansible.builtin.stat:
            path: /usr/bin/docker
          register: docker_executable

        - name: Docker | Download convenience script
          ansible.builtin.command: curl -fsSL https://get.docker.com -o get-docker.sh
          when: not docker_executable.stat.exists

        - name: Docker | Run convenience script
          become: true
          ansible.builtin.command: CHANNEL=stable sh get-docker.sh
          when: not docker_executable.stat.exists

        - name: Docker | Remove convenience script
          ansible.builtin.file:
            path: get-docker.sh
            state: absent
    - name: packages | Enable Docker buildx (Linux)
      become: true
      ansible.builtin.package:
        name: "{{ docker_buildx_package }}"
        state: latest
      when: ansible_system == "Linux"

    - name: packages | Install Docker Desktop (MacOS)
      ansible.builtin.command: "brew install --cask {{ item }}"
      with_items:
        - docker
      ignore_errors: true
      when: ansible_os_family == "Darwin"

    # - name: packages | install Docker packages (MacOS)
    #   homebrew:
    #     name:
    #       - docker-buildx
    #       - docker-compose
    #     state: latest
    #   when: ansible_os_family == "Darwin"

    - name: packages | Ensure docker service is not enabled (Linux)
      become: true
      ansible.builtin.service:
        name: "docker.socket"
        state: stopped
        enabled: false
      when: ansible_system == "Linux"

    - name: packages | Ensure docker service is not enabled (Linux)
      become: true
      ansible.builtin.service:
        name: docker
        state: stopped
        enabled: false
      when: ansible_system == "Linux"

    - name: packages | Ensure containerd service is not enabled (Linux)
      become: true
      ansible.builtin.service:
        name: containerd
        state: stopped
        enabled: false
      when: ansible_system == "Linux"

    - name: packages | Ensure systemd networkd wait online service is not enabled (Linux)
      become: true
      ansible.builtin.service:
        name: systemd-networkd-wait-online
        state: stopped
        enabled: false
      when: ansible_distribution in ["Artix Linux", "Archlinux", "Debian"]

    - name: "users | {{ user }} | ensure {{ user }} is in docker group (Linux)"
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: true
      when: ansible_system == "Linux"
