- name: packages | lua language server | install package (Archlinux)
  become: true
  package:
    name: lua-language-server
    state: latest
  when: ansible_os_family in ["Archlinux", "Artix Linux"]

- name: packages | lua language server | download release (Debian)
  become: true
  get_url:
    url: "https://github.com/sumneko/lua-language-server/releases/download/{{ lua_language_server_version }}/lua-language-server-{{ lua_language_server_version }}-linux-x64.tar.gz"
    dest: /tmp/lua-language-server.tar.gz
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | lua language server | ensure dir exists (Debian)
  become: true
  file:
    path: /opt/lua-language-server
    state: directory
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | lua language server | extract archive (Debian)
  become: true
  unarchive:
    src: /tmp/lua-language-server.tar.gz
    dest: /opt/lua-language-server
    owner: root
    group: root
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | lua language server | create alias script (Debian)
  become: true
  copy:
    src: packages/install_lualanguageserver.sh
    dest: "/home/{{ user }}/.local/bin/lua-language-server"
    owner: "{{ user }}"
    group: root
    mode: 0755
  when: ansible_distribution in ["Debian", "Pop!_OS"]

- name: packages | lua language server | install (MacOS)
  homebrew:
    name: lua-language-server
    state: latest
  when: ansible_os_family == "Darwin"
