# Samba share client
- name: samba
  become: true
  block:
    - name: samba | install client
      package:
        name:
          - smbclient
        state: latest

    - name: samba | create etc directory
      file:
        path: /etc/samba
        state: directory

    - name: samba | create configuration file
      file:
        path: /etc/samba/smb.conf
        state: touch
        modification_time: preserve
        access_time: preserve

    - name: samba | create credential directory
      file:
        path: /etc/samba/credentials
        state: directory
        owner: root
        mode: '0700'

    - name: samba | copy credential file
      template:
        src: credentials.j2
        dest: /etc/samba/credentials/share
        owner: root
        mode: '0600'

    - name: samba | create localAliases if not found
      file:
        path: "/home/{{ user }}/.config/localAliases"
        state: touch
        modification_time: preserve
        access_time: preserve
        owner: "{{ user }}"

    - name: samba | add alias
      lineinfile:
        path: "/home/{{ user }}/.config/localAliases"
        regexp: "^alias mount-{{ item }}=\"sudo mount --mkdir -t cifs //{{ samba_server }}/{{ item }} /mnt/fileserver/{{ item }} -o iocharset=utf8,credentials=/etc/samba/credentials/share,uid=1000\""
        line: "alias mount-{{ item }}=\"sudo mount --mkdir -t cifs //{{ samba_server }}/{{ item }} /mnt/fileserver/{{ item }} -o iocharset=utf8,credentials=/etc/samba/credentials/share,uid=1000\""
      with_items:
        - media
        - private
        - public
  when: ansible_distribution in ["Archlinux", "Artix Linux"]
