# Load distro specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_system == "Linux"

- name: Linux setup
  block:
    - import_tasks: packages/install_packages.yml
    - import_tasks: system_setup/kanshi.yml
  when: ansible_system == "Linux"
