---
# Load distro specific variables
- ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_system == "Linux"

- name: Linux setup
  when: ansible_system == "Linux"
  block:
    - ansible.builtin.import_tasks: packages/install_packages.yml
    - ansible.builtin.import_tasks: system_setup/kanshi.yml
