---
- name: packages | Dwm
  become: true
  when: ansible_system == "Linux" and (x11_install_type is not defined or x11_install_type == 'wm')
  block:
    - name: packages | dwm | clone repo
      ansible.builtin.git:
        repo: https://github.com/dixiedream/dwm
        dest: /tmp/dwm
        force: true

    - name: packages | dwm | install required dependencies (Debian)
      ansible.builtin.package:
        name:
          - build-essential
          - make
          - gcc
          - libharfbuzz-dev
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - xinit
          - xserver-xorg
          - x11-xserver-utils
        state: present
      when: ansible_os_family == "Debian"

    - name: packages | dwm | install
      community.general.make:
        target: install
        chdir: /tmp/dwm
