---
- name: packages | Libxft
  when: x11_install_type is not defined or x11_install_type == 'wm'
  become: true
  block:
    - name: packages | libxft | install (Archlinux)
      when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"]

      block:
        - name: packages | libxft | check if already installed
          ansible.builtin.stat:
            path: /usr/lib/libXft.so
          register: libxft_is_present

        - name: packages | libxft | install (Archlinux)
          ansible.builtin.import_tasks: ../../../base/tasks/packages/_install_aur_with_helper.yml
          vars:
            aur_package_name: libxft-git
            aur_creates: /usr/lib/libXft.so
          when: not libxft_is_present.stat.exists
    - name: packages | libxft | install required dep (Debian)
      ansible.builtin.apt:
        name:
          # - libxft2
          - libtool
          - xutils-dev
        state: latest
      when: ansible_facts["distribution"] in ["Debian", "Ubuntu"]

    - name: packages | Clone libxft patched version (Debian)
      ansible.builtin.git:
        repo: https://gitlab.freedesktop.org/xorg/lib/libxft.git
        dest: /tmp/libxft-bgra
        force: true
      when: ansible_facts["distribution"] in ["Debian", "Ubuntu"]
