- name: packages | dwm
  become: true
  block:
    - name: packages | dwm | clone repo
      git:
        repo: https://github.com/dixiedream/dwm
        dest: /tmp/dwm
        force: yes

    - name: packages | dwm | install required dependencies (Debian)
      package:
        name:
          - build-essential
          - make
          - gcc
          - libharfbuzz-dev
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - xinit
          - xserver-xorg
          - x11-xserver-utils
        state: present
      when: ansible_os_family == "Debian"

    - name: packages | dwm | install
      make:
        target: install
        chdir: /tmp/dwm
  when: ansible_system == "Linux"
