- name: packages | AUR helper
  become_user: ale
  block:
    - name: packages | AUR helper | check if already cloned
      stat:
        path: /tmp/yay
      register: yay_is_present

    - name: packages | AUR helper | clone Yay repo (Archlinux)
      become_user: ale
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
      when: not yay_is_present.stat.exists

    - name: packages | AUR helper | install Yay (Archlinux)
      become_user: ale
      command: makepkg --noconfirm -si
      args:
        chdir: /tmp/yay
        creates: /usr/bin/yay
      when: not yay_is_present.stat.exists
  when: ansible_os_family == "Archlinux"
