---
- name: Install wayland packages
  become: true
  block:
    - name: packages | Install wayland packages
      ansible.builtin.package:
        name:
          - foot
          - wl-clipboard
        state: latest

    - name: packages | Install wayland wm packages
      when: wayland_install_type is not defined or wayland_install_type == 'wm'
      block:
        - name: packages | Install wayland packages
          ansible.builtin.package:
            name:
              # General stuff
              - bemenu-wayland
              - dunst
              - grim
              - kanshi
              - playerctl
              - slurp
              - swaybg
              - swayimg
              - waybar
              # Hyprland stuff
              - hyprland
              - hypridle
              - hyprlock
              - xdg-desktop-portal-hyprland
              - uwsm
            state: latest

        - name: packages | install wayland packages | App2Unit
          when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"]
          block:
            - name: packages | app2unit | check if already installed
              ansible.builtin.stat:
                path: /usr/bin/app2unit
              register: pkg_is_present

            - name: packages | app2unit | App2Unit
              ansible.builtin.import_tasks: ../../../base/tasks/packages/_install_aur_with_helper.yml
              vars:
                aur_package_name: app2unit-git
                aur_creates: /usr/bin/app2unit
              when: not pkg_is_present.stat.exists
