# Using Windows audio plugins on Linux DAWs
---
- name: Yabridge
  become: true
  when: ansible_distribution in ["Archlinux", "Artix Linux"]
  block:
    - name: Yabridge | Install required packages
      ansible.builtin.package:
        name:
          - wine-staging
          - yabridge
          - yabridgectl

    - name: Yabridge | Create plugins folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ pro_audio_wine_prefix }}/Program Files/Steinberg/VstPlugins"
        - "{{ pro_audio_wine_prefix }}/Program Files/Common Files/VST3"
        - "{{ pro_audio_wine_prefix }}/Program Files/Common Files/CLAP"

    - name: Yabridge | Setup VST2 folder
      ansible.builtin.command: yabridgectl add "{{ pro_audio_wine_prefix }}/Program Files/Steinberg/VstPlugins"
    - name: Yabridge | Setup VST3 folder
      ansible.builtin.command: yabridgectl add "{{ pro_audio_wine_prefix }}/Program Files/Common Files/VST3"
    - name: Yabridge | Setup CLAP folder
      ansible.builtin.command: yabridgectl add "{{ pro_audio_wine_prefix }}/Program Files/Common Files/CLAP"
    - name: Yabridge | Sync plugins
      ansible.builtin.command: yabridgectl sync
