# Using Windows audio plugins on Linux DAWs
---
- name: Yabridge
  when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"]
  block:
    - name: Yabridge | Install required packages
      become: true
      ansible.builtin.package:
        name:
          - wine-staging
          - realtime

    - name: Yabridge | check if already installed
      ansible.builtin.stat:
        path: /usr/bin/yabridgectl
      register: pkg_is_present

    - name: Yabridge | Install package
      ansible.builtin.import_tasks: ../../base/tasks/packages/_install_aur_with_helper.yml
      vars:
        aur_package_name: yabridge-wine10-git
        aur_creates: /usr/bin/yabridge
      when: not pkg_is_present.stat.exists

    - name: Yabridge | Install package yabridgectl
      ansible.builtin.import_tasks: ../../base/tasks/packages/_install_aur_with_helper.yml
      vars:
        aur_package_name: yabridgectl-wine10-git
        aur_creates: /usr/bin/yabridgectl
      when: not pkg_is_present.stat.exists

    # Prevents the memory cap
    - name: "Yabridge | ensure {{ user }} is in realtime group (Linux)"
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        groups: realtime
        append: true

    - name: Yabridge | Create plugins folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
      with_items:
        - "/home/{{ user }}/.wine/drive_c/Program Files/Steinberg/VstPlugins"
        - "/home/{{ user }}/.wine/drive_c/Program Files/Common Files/VST3"
        - "/home/{{ user }}/.wine/drive_c/Program Files/Common Files/CLAP"

    - name: Yabridge | Setup VST2 folder
      ansible.builtin.command: yabridgectl add "/home/{{ user }}/.wine/drive_c/Program Files/Steinberg/VstPlugins"

    - name: Yabridge | Setup VST3 folder
      ansible.builtin.command: yabridgectl add "/home/{{ user }}/.wine/drive_c/Program Files/Common Files/VST3"

    - name: Yabridge | Setup CLAP folder
      ansible.builtin.command: yabridgectl add "/home/{{ user }}/.wine/drive_c/Program Files/Common Files/CLAP"

    - name: Yabridge | Sync plugins
      ansible.builtin.command: yabridgectl sync
