- name: users | ale | create group
  group:
    name: ale
    state: present

- name: users | ale | create user
  user:
    name: ale
    group: ale
    groups: "{{ sudo_group }}"
    state: present

- name: users | ale | create .ssh directory
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: ale
    group: ale 
    mode: 0700
  with_items:
    - { dir: '/home/ale/.ssh' }

- name: users | ale | check if key already exists
  stat:
    path: /home/ale/.ssh/id_rsa
  register: key_stat

- name: users | ale | generate ssh key
  openssh_keypair:
    path: /home/ale/.ssh/id_rsa
  when: not key_stat.stat.exists 
