---
- name: MacOS Setup
  when: ansible_os_family == "Darwin"
  block:
    - ansible.builtin.import_tasks: packages/install_brews.yml
    - ansible.builtin.import_tasks: packages/install_aerospace.yml
    - ansible.builtin.import_tasks: mac_os/activity_monitor.yml
    - ansible.builtin.import_tasks: mac_os/address_book.yml
    - ansible.builtin.import_tasks: mac_os/dashboard.yml
    - ansible.builtin.import_tasks: mac_os/disk_utility.yml
    - ansible.builtin.import_tasks: mac_os/dock.yml
    - ansible.builtin.import_tasks: mac_os/finder.yml
    - ansible.builtin.import_tasks: mac_os/font.yml
    - ansible.builtin.import_tasks: mac_os/global.yml
    - ansible.builtin.import_tasks: mac_os/hot_corners.yml
    - ansible.builtin.import_tasks: mac_os/locale.yml
    - ansible.builtin.import_tasks: mac_os/mac_app_store.yml
    - ansible.builtin.import_tasks: mac_os/mail.yml
    - ansible.builtin.import_tasks: mac_os/messages.yml
    - ansible.builtin.import_tasks: mac_os/photos.yml
    - ansible.builtin.import_tasks: mac_os/quicktime.yml
    - ansible.builtin.import_tasks: mac_os/tap_to_click.yml
    - ansible.builtin.import_tasks: mac_os/text_edit.yml
    - ansible.builtin.import_tasks: mac_os/time_machine.yml
    - ansible.builtin.import_tasks: system_setup/dotfiles.yml
