---
- name: Gnome setup
  when: ansible_system == "Linux"
  block:
    - ansible.builtin.import_tasks: packages/install_packages.yml
    - ansible.builtin.import_tasks: packages/install_psutil.yml
    - ansible.builtin.import_tasks: packages/install_foot.yml
    - ansible.builtin.import_tasks: packages/install_pop_shell.yml
    - ansible.builtin.import_tasks: packages/debloat.yml
    - ansible.builtin.import_tasks: gnome/disable_extensions.yml
    - ansible.builtin.import_tasks: gnome/disable_notifications.yml
    - ansible.builtin.import_tasks: gnome/appearance.yml
    - ansible.builtin.import_tasks: gnome/keybindings.yml
    - ansible.builtin.import_tasks: gnome/input-sources.yml
    - ansible.builtin.import_tasks: gnome/pop-shell.yml
    - ansible.builtin.import_tasks: gnome/privacy.yml
    - ansible.builtin.import_tasks: gnome/tracker.yml
