- name: Gnome setup
  block:
    - import_tasks: packages/install_psutil.yml
    - import_tasks: packages/install_alacritty.yml
    - import_tasks: packages/debloat.yml
    - import_tasks: gnome/disable_extensions.yml
    - import_tasks: gnome/appearance.yml
    - import_tasks: gnome/keybindings.yml
    - import_tasks: gnome/input-sources.yml
    - import_tasks: gnome/pop-shell.yml
    - import_tasks: gnome/privacy.yml
    - import_tasks: gnome/tracker.yml
  when: ansible_system == "Linux"
