- name: system setup | activity monitor | show the main window when launching Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor 
    key: OpenMainWindow 
    type: bool 
    value: true

- name: system setup | activity monitor | visualize CPU usage in the Activity Monitor Dock icon
  osx_defaults:
    domain: com.apple.ActivityMonitor 
    key: IconType 
    type: int 
    value: 5

- name: system setup | activity monitor | show all processes in Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor 
    key: ShowCategory 
    type: int 
    value: 0

- name: system setup | activity monitor | sort Activity Monitor results by CPU usage
  osx_defaults:
    domain: com.apple.ActivityMonitor 
    key: SortColumn 
    type: string 
    value: "CPUUsage"

- name: system setup | activity monitor | sort Activity Monitor results by CPU usage 2
  osx_defaults:
    domain: com.apple.ActivityMonitor 
    key: SortDirection 
    type: int 
    value: 0
