- name: system setup | disk utility | Enable the debug menu in Disk Utility
  osx_defaults:
    domain: com.apple.DiskUtility 
    key: DUDebugMenuEnabled 
    type: bool 
    value: true

- name: system setup | disk utility | Enable the debug menu in Disk Utility 2
  osx_defaults:
    domain: com.apple.DiskUtility 
    key: advanced-image-options 
    type: bool 
    value: true
