- name: mac os | install brews formulas
  homebrew:
    name:
      - atool
      - fzf
      - git
      - gzip
      - htop
      - jq
      - lf
      - ncdu
      - neofetch
      - neovim
      - p7zip
      - ripgrep
      - koekeishiya/formulae/skhd
      - unar
      - unzip
      - koekeishiya/formulae/yabai
      - yt-dlp
      - zip
    state: latest

- name: mac os | install brew casks
  command: "brew install --cask {{ item }}"
  with_items:
      - alacritty
      - appcleaner
      - brave-browser
      - mpv
      - onyx
      - the-unarchiver
      - transmission
  ignore_errors: true

- name: mac os | start required brews
  command: "brew services start {{ item }}"
  with_items:
    - skhd
    - yabai
  changed_when: false
  ignore_errors: true

