- name: system setup | language
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - "en"

- name: system setup | locale
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_US@currency=EUR"

- name: system setup | measurement units
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: "Centimeters"

- name: system setup | temp unit
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleTemperatureUnit
    type: string
    value: "Celsius"

- name: system setup | metrics units
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true

- name: system setup | disable language menu in the corner of boot screen
  osx_defaults:
    path: /Library/Preferences
    domain: com.apple.loginwindow
    key: showInputMenu
    type: bool
    value: false
  become: true

- name: system setup | timezone
  shell: systemsetup -settimezone "Europe/Rome" > /dev/null
  become: true
