- name: system setup | mail | Disable reply animations
  osx_defaults:
    domain: com.apple.mail
    key: DisableReplyAnimations
    type: bool
    value: true

- name: system setup | mail | Disable send animations
  osx_defaults:
    domain: com.apple.mail
    key: DisableSendAnimations
    type: bool
    value: true

- name: system setup | mail | Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>`
  osx_defaults:
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: false

- name: system setup | mail | Display emails in threaded mode, sorted by date (oldest at the top)
  shell: defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"

- name: system setup | mail | Display emails in threaded mode, sorted by date (oldest at the top) 2
  shell: defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"

- name: system setup | mail | Display emails in threaded mode, sorted by date (oldest at the top) 3
  shell: defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

- name: system setup | mail | Disable inline attachments (just show the icons)
  osx_defaults:
    domain: com.apple.mail
    key: DisableInlineAttachmentViewing
    type: bool
    value: true

- name: system setup | mail | Disable automatic spell checking
  osx_defaults:
    domain: com.apple.mail
    key: SpellCheckingBehavior
    type: string
    value: "NoSpellCheckingEnabled"

- name: system setup | mail | restart
  shell: killall Mail
  changed_when: false
  ignore_errors: true
