- name: system setup | safari | privacy | don’t send search queries to Apple
  osx_defaults:
    domain: com.apple.Safari 
    key: UniversalSearchEnabled 
    type: bool 
    value: false

- name: system setup | safari | Privacy | disable search suggestions
  osx_defaults:
    domain: com.apple.Safari 
    key: SuppressSearchSuggestions 
    type: bool 
    value: true

- name: system setup | safari | Press Tab to highlight each item on a web page
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
    - defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true
  changed_when: false

- name: system setup | safari | Show the full URL in the address bar 
  osx_defaults:
    domain: com.apple.Safari 
    key: ShowFullURLInSmartSearchField 
    type: bool 
    value: true

- name: system setup | safari | Set home page to `about blank` for faster loading
  osx_defaults:
    domain: com.apple.Safari 
    key: HomePage 
    type: string 
    value: "about:blank"

- name: system setup | safari | Prevent from opening ‘safe’ files automatically after downloading
  osx_defaults:
    domain: com.apple.Safari 
    key: AutoOpenSafeDownloads 
    type: bool 
    value: false

- name: system setup | safari | Allow hitting the Backspace key to go to the previous page in history
  osx_defaults:
    domain: com.apple.Safari 
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled 
    type: bool 
    value: true

- name: system setup | safari | Hide bookmarks bar by default
  osx_defaults:
    domain: com.apple.Safari 
    key: ShowFavoritesBar 
    type: bool 
    value: false

- name: system setup | safari | Hide sidebar in Top Sites
  osx_defaults:
    domain: com.apple.Safari 
    key: ShowSidebarInTopSites 
    type: bool 
    value: false

- name: system setup | safari | Disable thumbnail cache for History and Top Sites
  osx_defaults:
    domain: com.apple.Safari 
    key: DebugSnapshotsUpdatePolicy 
    type: int 
    value: 2

- name: system setup | safari | Enable debug menu
  osx_defaults:
    domain: com.apple.Safari 
    key: IncludeInternalDebugMenu 
    type: bool 
    value: true

- name: system setup | safari | Make search banners default to Contains instead of Starts With
  osx_defaults:
    domain: com.apple.Safari 
    key: FindOnPageMatchesWordStartsOnly 
    type: bool 
    value: false

- name: system setup | safari | Remove useless icons from bookmarks bar
  osx_defaults:
    domain: com.apple.Safari 
    key: ProxiesInBookmarksBar 
    type: string
    value: "()"

- name: system setup | safari | Enable the Develop menu and the Web Inspector
  command: "defaults write com.apple.Safari {{ item }}"
  with_items:
    - IncludeDevelopMenu -bool true
    - WebKitDeveloperExtrasEnabledPreferenceKey -bool true
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
  changed_when: false

- name: system setup | safari | Add a context menu item for showing the Web Inspector in web views
  osx_defaults:
    domain: NSGlobalDomain 
    key: WebKitDeveloperExtras 
    type: bool 
    value: true

- name: system setup | safari | Enable continuous spellchecking
  osx_defaults:
    domain: com.apple.Safari 
    key: WebContinuousSpellCheckingEnabled 
    type: bool 
    value: true

- name: system setup | safari | Disable auto-correct
  osx_defaults:
    domain: com.apple.Safari 
    key: WebAutomaticSpellingCorrectionEnabled 
    type: bool 
    value: false

- name: system setup | safari | Disable AutoFill from address book
  osx_defaults:
    domain: com.apple.Safari 
    key: AutoFillFromAddressBook 
    type: bool 
    value: false

- name: system setup | safari | Disable AutoFill from passwords
  osx_defaults:
    domain: com.apple.Safari 
    key: AutoFillPasswords 
    type: bool 
    value: false

- name: system setup | safari | Disable AutoFill from credit card data
  osx_defaults:
    domain: com.apple.Safari 
    key: AutoFillCreditCardData 
    type: bool 
    value: false

- name: system setup | safari | Disable AutoFill from miscellaneous forms
  osx_defaults:
    domain: com.apple.Safari 
    key: AutoFillMiscellaneousForms 
    type: bool 
    value: false

- name: system setup | safari | Warn about fraudulent websites
  osx_defaults:
    domain: com.apple.Safari 
    key: WarnAboutFraudulentWebsites 
    type: bool 
    value: true

- name: system setup | safari | Disable plug-ins
  command: "defaults write com.apple.Safari {{ item }}"
  with_items:
    - WebKitPluginsEnabled -bool false
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false
  changed_when: false

- name: system setup | safari | Disable Java
  command: "defaults write com.apple.Safari {{ item }}"
  with_items:
    - WebKitJavaEnabled -bool false
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false
  changed_when: false

- name: system setup | safari | Block pop-up windows
  command: "defaults write com.apple.Safari {{ item }}"
  with_items:
    - WebKitJavaScriptCanOpenWindowsAutomatically -bool false
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false
  changed_when: false

- name: system setup | safari | Disable auto-playing video
  osx_defaults:
    domain: com.apple.Safari 
    key: WebKitMediaPlaybackAllowsInline 
    type: bool 
    value: false

- name: system setup | safari | Disable auto-playing video 2
  osx_defaults:
    domain: com.apple.SafariTechnologyPreview 
    kry: WebKitMediaPlaybackAllowsInline 
    type: bool 
    value: false

- name: system setup | safari | Disable auto-playing video 3
  osx_defaults:
    domain: com.apple.Safari 
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback 
    type: bool 
    value: false

- name: system setup | safari | Disable auto-playing video 4
  osx_defaults:
    domain: com.apple.SafariTechnologyPreview 
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback 
    type: bool 
    value: false

- name: system setup | safari | Enable “Do Not Track”
  osx_defaults:
    domain: com.apple.Safari 
    key: SendDoNotTrackHTTPHeader 
    type: bool 
    value: true

- name: system setup | safari | Update extensions automatically
  osx_defaults:
    domain: com.apple.Safari 
    key: InstallExtensionUpdatesAutomatically 
    type: bool 
    value: true

- name: system setup | safari | restart
  shell: killall Safari
  changed_when: false
