- name: gnome | appearance
  become_user: "{{ user }}"
  block:
    - name: gnome | appearance | setup desktop theme
      vars:
        base_key: "/org/gnome/desktop/interface"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/color-scheme", value: "'prefer-dark'" }
        - { key: "{{ base_key }}/enable-animations", value: "false" }

    - name: gnome | appearance | enable night colors
      vars:
        base_key: "/org/gnome/settings-daemon/plugins/color"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/night-light-enabled", value: "true" }
        - { key: "{{ base_key }}/night-light-temperature", value: "uint32 3223" }
