---
- name: gnome | Appearance
  become_user: "{{ user }}"
  block:
    - name: gnome | appearance | setup desktop theme
      vars:
        base_key: "/org/gnome/desktop/interface"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/color-scheme", value: "'prefer-dark'" }
        - { key: "{{ base_key }}/enable-animations", value: "false" }

    - name: gnome | appearance | enable night colors
      vars:
        base_key: "/org/gnome/settings-daemon/plugins/color"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/night-light-enabled", value: "true" }
        - { key: "{{ base_key }}/night-light-temperature", value: "uint32 3223" }

    - name: gnome | appearance | profile cleaning
      ansible.builtin.lineinfile:
        dest: "/home/{{ user }}/.zprofile"
        regexp: "^{{ item }}"
        line: "#{{ item }}"
      with_items:
        - "export GTK_THEME"
        - "export GTK2_RC_FILES"
        - "export PASSWORD_STORE_DIR"
        - "export QT_QPA_PLATFORMTHEME"
        - "export SUDO_ASKPASS"
