---
- name: gnome | Input sources
  vars:
    base_key: "/org/gnome/desktop/input-sources"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "{{ base_key }}/xkb-options", value: "['caps:ctrl_modifier']" }
