---
- name: gnome | Keybindings
  become_user: "{{ user }}"
  block:
    - name: gnome | keybindings | window management | Ubuntu
      vars:
        base_key: "/org/gnome/desktop/wm/keybindings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/close", value: "['<Shift><Super>c']" }
        - { key: "{{ base_key }}/maximize", value: "@as []" }
        - { key: "{{ base_key }}/move-to-workspace-1", value: "['<Shift><Super>1']" }
        - { key: "{{ base_key }}/move-to-workspace-2", value: "['<Shift><Super>2']" }
        - { key: "{{ base_key }}/move-to-workspace-3", value: "['<Shift><Super>3']" }
        - { key: "{{ base_key }}/move-to-workspace-4", value: "['<Shift><Super>4']" }
        - { key: "{{ base_key }}/switch-applications", value: "['<Shift>Tab']" }
        - { key: "{{ base_key }}/switch-applications-backward", value: "['<Shift><Super>Tab']" }
        - { key: "{{ base_key }}/switch-to-workspace-1", value: "['<Super>1']" }
        - { key: "{{ base_key }}/switch-to-workspace-2", value: "['<Super>2']" }
        - { key: "{{ base_key }}/switch-to-workspace-3", value: "['<Super>3']" }
        - { key: "{{ base_key }}/switch-to-workspace-4", value: "['<Super>4']" }
        - { key: "{{ base_key }}/switch-to-workspace-last", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-left", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-right", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-up", value: "@as []" }
        - { key: "{{ base_key }}/unmaximize", value: "@as []" }
        - { key: "{{ base_key }}/toggle-fullscreen", value: "['<Super>f']" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | keybindings | window management | Pop OS
      vars:
        base_key: "/org/gnome/desktop/wm/keybindings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/activate-window-menu", value: "@as []" }
        - { key: "{{ base_key }}/close", value: "['<Alt>F4', '<Shift><Super>C']" }
        - { key: "{{ base_key }}/cycle-group", value: "@as []" }
        - { key: "{{ base_key }}/cycle-group-backward", value: "@as []" }
        - { key: "{{ base_key }}/cycle-panels", value: "@as []" }
        - { key: "{{ base_key }}/cycle-panels-backward", value: "@as []" }
        - { key: "{{ base_key }}/cycle-windows", value: "@as []" }
        - { key: "{{ base_key }}/cycle-windows-backward", value: "@as []" }
        - { key: "{{ base_key }}/move-to-workspace-1", value: "['<Shift><Super>Home', '<Shift><Super>exclam']" }
        - { key: "{{ base_key }}/move-to-workspace-2", value: "['<Shift><Super>quotedbl']" }
        - { key: "{{ base_key }}/move-to-workspace-3", value: "['<Shift><Super>sterling']" }
        - { key: "{{ base_key }}/move-to-workspace-4", value: "['<Shift><Super>dollar']" }
        - { key: "{{ base_key }}/move-to-workspace-last", value: "@as []" }
        - { key: "{{ base_key }}/switch-group", value: "@as []" }
        - { key: "{{ base_key }}/switch-group-backward", value: "@as []" }
        - { key: "{{ base_key }}/switch-input-source", value: "@as []" }
        - { key: "{{ base_key }}/switch-input-source-backward", value: "@as []" }
        - { key: "{{ base_key }}/switch-panels", value: "@as []" }
        - { key: "{{ base_key }}/switch-panels-backward", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-1", value: "['<Super>1']" }
        - { key: "{{ base_key }}/switch-to-workspace-2", value: "['<Super>2']" }
        - { key: "{{ base_key }}/switch-to-workspace-3", value: "['<Super>3']" }
        - { key: "{{ base_key }}/switch-to-workspace-4", value: "['<Super>4']" }
        - { key: "{{ base_key }}/switch-to-workspace-up", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-down", value: "@as []" }
        - { key: "{{ base_key }}/switch-to-workspace-last", value: "@as []" }
        - { key: "{{ base_key }}/toggle-fullscreen", value: "['<Super>f']" }
      when: ansible_distribution in ["Pop!_OS"]

    - name: gnome | keybindings | media keys | Ubuntu
      vars:
        base_key: "/org/gnome/settings-daemon/plugins/media-keys"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        # - { key: "{{ base_key }}/custom-keybindings", value: "['{{ base_key }}/custom-keybindings/custom0/']" }
        - { key: "{{ base_key }}/logout", value: "['<Shift><Super>q']" }
        - { key: "{{ base_key }}/next", value: "['<Control><Alt>Right']" }
        - { key: "{{ base_key }}/play", value: "['<Control><Alt>Up']" }
        - { key: "{{ base_key }}/previous", value: "['<Control><Alt>Left']" }
        - { key: "{{ base_key }}/screensaver", value: "['<Alt><Super>l']" }
        - { key: "{{ base_key }}/terminal", value: "['<Super>Return']" }
        - { key: "{{ base_key }}/volume-down", value: "['<Alt>Down']" }
        - { key: "{{ base_key }}/volume-mute", value: "['<Alt>m']" }
        - { key: "{{ base_key }}/volume-up", value: "['<Alt>Up']" }
        - { key: "{{ base_key }}/www", value: "['<Super>q']" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | keybindings | media keys | Pop Os
      vars:
        base_key: "/org/gnome/settings-daemon/plugins/media-keys"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/custom-keybindings", value: "['{{ base_key }}/custom-keybindings/custom0/']" }
        - { key: "{{ base_key }}/email", value: "@as []" }
        - { key: "{{ base_key }}/help", value: "@as []" }
        - { key: "{{ base_key }}/home", value: "@as []" }
        - { key: "{{ base_key }}/logout", value: "['<Shift><Super>q']" }
        - { key: "{{ base_key }}/next", value: "['<Primary><Alt>Right']" }
        - { key: "{{ base_key }}/play", value: "['<Primary><Alt>Up']" }
        - { key: "{{ base_key }}/previous", value: "['<Primary><Alt>Left']" }
        - { key: "{{ base_key }}/screensaver", value: "['<Alt><Super>l']" }
        - { key: "{{ base_key }}/terminal", value: "['<Super>Return']" }
        - { key: "{{ base_key }}/volume-down", value: "['<Alt>Down']" }
        - { key: "{{ base_key }}/volume-mute", value: "['<Alt>m']" }
        - { key: "{{ base_key }}/volume-up", value: "['<Alt>Up']" }
        - { key: "{{ base_key }}/www", value: "['<Super>q']" }
      when: ansible_distribution in ["Pop!_OS"]

    - name: gnome | keybindings | LF
      vars:
        base_key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/binding", value: "'<Super>n'" }
        - { key: "{{ base_key }}/command", value: "'foot -e lf'" }
        - { key: "{{ base_key }}/name", value: "'LF'" }

    - name: gnome | keybindings | change window focus on mouse hover
      vars:
        base_key: "/org/gnome/desktop/wm/preferences"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/focus-mode", value: "'sloppy'" }
      when: ansible_distribution in ["Pop!_OS"]

    - name: gnome | keybindings | pop shell
      vars:
        base_key: "/org/gnome/shell/extensions/pop-shell"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/activate-launcher", value: "@as []" }
        - { key: "{{ base_key }}/management-orientation", value: "@as []" }
        - { key: "{{ base_key }}/pop-monitor-right", value: "['<Shift><Super>Right', '<Shift><Super>KP_Right', '<Shift><Super>l', '<Super>o']" }
        - { key: "{{ base_key }}/tile-enter", value: "@as []" }
        - { key: "{{ base_key }}/tile-orientation", value: "@as []" }
        - { key: "{{ base_key }}/toggle-tiling", value: "['<Super>y', '<Super>space']" }
      when: ansible_distribution in ["Pop!_OS"]

    - name: gnome | keybindings | tilingshell | Ubuntu
      vars:
        base_key: "/org/gnome/shell/extensions/tilingshell"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/enable-autotiling", value: "true" }
        - { key: "{{ base_key }}/inner-gaps", value: "uint32 3" }
        - { key: "{{ base_key }}/layouts-json", value: "'[{\"id\":\"806173\",\"tiles\":[{\"x\":0,\"y\":0,\"width\":1,\"height\":1,\"groups\":[]}]}]'" }
        - { key: "{{ base_key }}/outer-gaps", value: "uint32 3" }
        - key: "{{ base_key }}/overridden-settings"
          value: "{\"org.gnome.mutter.keybindings\":{\"toggle-tiled-right\":\"['<Super>Right']\",\"toggle-tiled-left\":\"['<Super>Left']\"},\"org.gnome.desktop.wm.keybindings\"\
            :{\"maximize\":\"@as []\",\"unmaximize\":\"@as []\"},\"org.gnome.mutter\":{\"edge-tiling\":\"true\"}}"
        - { key: "{{ base_key }}/selected-layouts", value: "[['806173'], ['806173'], ['806173'], ['806173']]" }
        - { key: "{{ base_key }}/snap-assistant-animation-time", value: "uint32 0" }
        - { key: "{{ base_key }}/tile-preview-animation-time", value: "uint32 0" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | keybindings | mutter | Ubuntu
      vars:
        base_key: "/org/gnome/mutter"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/dynamic-workspaces", value: "false" }
        - { key: "{{ base_key }}/edge-tiling", value: "false" }
        - { key: "{{ base_key }}/workspaces-only-on-primary", value: "false" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | keybindings | mutter keybindings | Ubuntu
      vars:
        base_key: "/org/gnome/mutter/keybindings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/toggle-tiled-left", value: "@as []" }
        - { key: "{{ base_key }}/toggle-tiled-right", value: "@as []" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | keybindings | shell
      vars:
        base_key: "/org/gnome/shell/keybindings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/toggle-message-tray", value: "['<Shift><Super>d']" }

    - name: gnome | keybindings | shell
      vars:
        base_key: "/org/gnome/shell/keybindings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/focus-active-notifications", value: "@as []" }
        - { key: "{{ base_key }}/screenshot", value: "@as []" }
        - { key: "{{ base_key }}/screenshot-window", value: "@as []" }
        - { key: "{{ base_key }}/show-screen-recording-ui", value: "@as []" }
        - { key: "{{ base_key }}/toggle-overview", value: "@as []" }
      when: ansible_distribution in ["Pop!_OS"]
