- name: gnome | pop-shell
  become_user: "{{ user }}"
  block:
    - name: gnome | pop-shell | setup
      vars:
        base_key: "/org/gnome/shell/extensions/pop-shell"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/gap-inner", value: "uint32 1"}
        - { key: "{{ base_key }}/gap-outer", value: "uint32 1"}
        - { key: "{{ base_key }}/show-title", value: "false"}
        - { key: "{{ base_key }}/show-skip-taskbar", value: "false"}
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
