---
- name: gnome | Privacy
  become_user: "{{ user }}"
  block:
    - name: gnome | privacy | setup cleanup policy
      vars:
        base_key: "/org/gnome/desktop/privacy"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/recent-files-max-age", value: "7" }
        - { key: "{{ base_key }}/remove-old-temp-files", value: "true" }
        - { key: "{{ base_key }}/remove-old-trash-files", value: "true" }

    - name: gnome | privacy | Ubuntu
      vars:
        base_key: "/org/gnome/desktop/privacy"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/old-files-age", value: "uint32 7" }
      when: ansible_distribution in ["Ubuntu"]

    - name: gnome | privacy | setup cleanup policy
      vars:
        base_key: "/org/gnome/desktop/privacy"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: "{{ base_key }}/report-technical-problems", value: "false" }
      when: ansible_distribution in ["Pop!_OS"]
