- name: packages | foot
  block:
    - name: packages | foot | install terminal emulator
      become: true
      package:
        name: foot
        state: latest
      when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
