- name: packages | foot
  become: true
  block:
    - name: packages | foot | install terminal emulator
      package:
        name: foot
        state: latest

    - name: packages | foot | set as default
      community.general.alternatives:
        name: x-terminal-emulator
        path: /usr/bin/foot
        state: auto
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
