- name: packages | foot
  block:
    - name: packages | foot | install terminal emulator
      become: true
      package:
        name: foot
        state: latest
      when: ansible_distribution in ["Pop!_OS"]

    - name: packages | foot | install terminal emulator
      community.general.snap:
        name: foot
        state: latest
      when: ansible_distribution in ["Ubuntu"]
