- name: packages | alacritty
  block:
    - name: packages | alacritty | install terminal emulator
      become: true
      package:
        name: alacritty
        state: latest
      when: ansible_distribution in ["Pop!_OS"]

    - name: packages | alacritty | install terminal emulator
      community.general.snap:
        name: alacritty
        state: latest
      when: ansible_distribution in ["Ubuntu"]
