- name: packages | install LF file manager
  become: true
  vars:
    lf_dir: "/home/{{ user }}/.config/lf"
  block:
    - name: packages | lf | install (Archlinux)
      become_user: "{{ user }}"
      command: yay -S --noconfirm lf
      args:
        creates: /usr/bin/lf
      when: ansible_os_family == "Archlinux"

    - name: packages | lf | install (Debian)
      apt:
        name: lf
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: packages | lf | install (Other Linux distros)
      unarchive:
        src: "https://github.com/gokcehan/lf/releases/download/{{ lf_version }}/lf-linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
      when: ansible_distribution not in ["Archlinux", "Debian", "Ubuntu"]

    - name: packages | lf | check if lf config folder exists
      stat:
       path: "{{ lf_dir }}"
      register: lf_folder

    - name: packages | lf | create lf config folder
      become_user: "{{ user }}"
      file:
        path: "{{ lf_dir }}"
        state: directory
      when: lf_folder.stat.exists == false

    - name: packages | lf | copy conf file
      become_user: "{{ user }}"
      copy:
        src: packages/lfrc
        dest: "/home/{{ user }}/.config/lf/lfrc"
