---
- name: packages | Pop-shell
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  block:
    - name: packages | pop-shell | clone aleDVirgo fork
      ansible.builtin.git:
        repo: https://github.com/aleDVirgo/pop-shell
        dest: /tmp/pop-shell
        force: true

    - name: packages | pop-shell | install extension
      community.general.make:
        target: local-install
        chdir: /tmp/pop-shell
