- name: packages | alacritty
  block:
    - name: packages | alacritty | install terminal emulator
      become: true
      package:
        name: alacritty
        state: latest
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]
