---
- name: ansible setup | Ensure ansible is the latest version
  become: true
  ansible.builtin.package:
    name:
      - ansible
      - "{{ python_passlib_package }}" # Used to create password hashes in ansible
    state: latest
