- name: ansible setup | ensure ansible is the latest version
  become: true
  package:
    name:
      - ansible
      - "{{ python_passlib_package }}" # Used to create password hashes in ansible
    state: latest
