- name: packages | debloat Ubuntu
  block:
    - name: packages | debloat Ubuntu | remove snaps
      snap:
        name:
          - firefox
          - snap-store
          - firmware-updater
          - gnome-42-2204
          - gtk-common-themes
          - snapd-desktop-integration
          - bare
          - core22
          - snapd
        state: absent

    - name: packages | debloat Ubuntu | remove snapd
      become: true
      apt:
        name: snapd
        state: absent

    - name: packages | debloat Ubuntu | prevent snap reinstall
      become: true
      ansible.builtin.copy:
        src: nosnap.pref
        dest: /etc/apt/preferences.d/nosnap.pref
  when: ansible_distribution in ["Ubuntu"]
