- name: packages | auto-cpufreq
  become: true
  block:
    - name: packages | auto-cpufreq | Archlinux
      block:
        - name: packages | auto-cpufreq | check if already installed
          stat:
            path: /usr/bin/auto-cpufreq
          register: pkg_is_present

        - name: packages | auto-cpufreq | enable passwordless pacman
          become: true
          ansible.builtin.replace:
            path: "/etc/sudoers.d/{{ user }}"
            regexp: '^(Cmnd_Alias.*)$'
            replace: '\1, /usr/bin/pacman'
            validate: 'visudo -cf %s'
          when: not pkg_is_present.stat.exists

        - name: packages | auto-cpufreq | install AUR package (Archlinux)
          become_user: "{{ user }}"
          command: "{{ aur_helper_name }} -S --noconfirm --removemake auto-cpufreq"
          args:
            creates: /usr/bin/auto-cpufreq
          when: not pkg_is_present.stat.exists

        - name: packages | auto-cpufreq | disable passwordless pacman
          become: true
          ansible.builtin.replace:
            path: "/etc/sudoers.d/{{ user }}"
            regexp: '^(Cmnd_Alias[^\n]*?)(?:\s*,\s*/usr/bin/pacman)?\s*$'
            replace: '\1'
            validate: 'visudo -cf %s'
          when: not pkg_is_present.stat.exists
      when: ansible_distribution in ["Archlinux", "Artix Linux"] and ansible_service_mgr == 'systemd'

    - name: packages | auto-cpufreq | Debian
      block:
        - name: packages | auto-cpufreq | clone repo (Debian)
          git:
            repo: https://github.com/AdnanHodzic/auto-cpufreq.git
            dest: ~/src/auto-cpufreq

        - name: packages | auto-cpufreq | install (Debian)
          shell: ./auto-cpufreq-installer --install
          args:
            chdir: ~/src/auto-cpufreq
            creates: /usr/local/bin/auto-cpufreq

        - name: packages | auto-cpufreq | start and enable (Debian)
          command: auto-cpufreq --install
          ignore_errors: yes
      when: ansible_os_family in ["Debian"] and ansible_service_mgr == 'systemd'

    - name: packages | auto-cpufreq | start and enable (Systemd)
      service:
        name: auto-cpufreq
        state: started
        enabled: yes
      when: ansible_service_mgr == 'systemd'

    - name: packages | auto-cpufreq | Runit
      block:
        - name: packages | auto-cpufreq | clone repo
          git:
            repo: https://github.com/AdnanHodzic/auto-cpufreq
            dest: /tmp/auto-cpufreq
            force: yes

        - name: packages | auto-cpufreq | create conf file
          shell: sh /tmp/auto-cpufreq/auto-cpufreq-installer --install
      when: ansible_service_mgr != 'systemd'
  when: ansible_form_factor is defined and ansible_form_factor == "Notebook"
