- name: packages | dwm | clone repo 
  git:
    repo: https://github.com/dixiedream/dwm
    dest: ~/src/dwm

- name: packages | dwm | install required dependencies (Debian) 
  package:
    name: 
      - make
      - gcc
      - libharfbuzz-dev
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | dwm | install dwm 
  make:
    target: install
    chdir: ~/src/dwm
