- name: packages | install Nordic theme (Archlinux)
  pacman:
    name:
      - nordic-theme-git
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: packages | download and install Nordic theme (Debian)
  unarchive:
    src: "https://github.com/EliverLara/Nordic/releases/download/{{ nordic_theme_version }}/Nordic.tar.xz"
    dest: /usr/share/themes
    remote_src: yes
  when: ansible_os_family == "Debian"
