- name: packages | st | clone repo 
  git:
    repo: https://github.com/dixiedream/st
    dest: /tmp/st
    force: yes

- name: packages | st | install st 
  make:
    target: install
    chdir: /tmp/st
