---
- name: packages | Twingate
  become: true
  when: ansible_facts["form_factor"] is defined and ansible_facts["form_factor"] in ["Notebook", "Other"]
  block:
    - name: packages | twingate | Archlinux
      when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"]

      block:
        - name: packages | twingate | check if already installed
          ansible.builtin.stat:
            path: /usr/bin/twingate
          register: pkg_is_present

        - name: packages | twingate | install package (Archlinux)
          ansible.builtin.import_tasks: _install_aur_with_helper.yml
          vars:
            aur_package_name: twingate-client
            aur_creates: /usr/bin/twingate
          when: not pkg_is_present.stat.exists
    - name: packages | twingate | debian
      when: ansible_facts["os_family"] == "Debian"
      block:
        - name: packages | twingate | add repo to sources list (Debian)
          ansible.builtin.apt_repository:
            repo: deb [trusted=yes] https://packages.twingate.com/apt/ /
            state: present
            filename: twingate

        - name: packages | twingate | install package (Debian)
          ansible.builtin.package:
            name: twingate
            update_cache: true
