- name: packages | auto-cpufreq | install AUR package (Archlinux)
  pacman:
    name:
      - auto-cpufreq
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: packages | auto-cpufreq | clone repo (Debian)
  git:
    repo: https://github.com/AdnanHodzic/auto-cpufreq.git
    dest: ~/src/auto-cpufreq
  when: ansible_os_family == "Debian"

- name: packages | auto-cpufreq | install (Debian)
  shell: ./auto-cpufreq-installer --install
  args:
    chdir: ~/src/auto-cpufreq
    creates: /usr/local/bin/auto-cpufreq
  when: ansible_os_family == "Debian"

- name: packages | auto-cpufreq | start and enable (Debian)
  command: auto-cpufreq --install
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: packages | auto-cpufreq | check is started and enabled
  service: 
    name: auto-cpufreq
    state: started
    enabled: yes
