---
- name: packages | Lazygit
  become: true
  block:
    - name: packages | lazygit | install
      ansible.builtin.package:
        name: lazygit
        state: latest
      when: ansible_distribution in ["Artix Linux", "Archlinux", "Debian"]

    - name: packages | lazygit | ubuntu
      ansible.builtin.unarchive:
        src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        mode: "0755"
      when: ansible_distribution in ["Ubuntu", "Pop!_OS"]
