- name: packages | neovim | install package (Arch and debian)
  become: true
  package:
    name: neovim
    state: latest
  when: ansible_distribution in ["Archlinux", "Artix Linux", "Debian"]

- name: packages | neovim | install package (ubuntu)
  become: true
  block:
    - name: packages | neovim | add repo
      apt_repository:
        repo: ppa:neovim-ppa/unstable

    - name: packages | neovim | install package (Arch and debian)
      package:
        name: neovim
        state: latest
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
