- name: packages | neovim | install package
  become: true
  package:
    name: neovim
    state: latest
  when: ansible_distribution in ["Archlinux", "Artix Linux"]

- name: packages | neovim (Debian)
  become: true
  block:
    - name: packages | neovim (Debian) | add "unstable" repository
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'
        state: present

    - name: packages | neovim (Debian) | update apt cache
      apt:
        update_cache: yes

    - name: packages | neovim (Debian) | install
      apt:
        name: neovim
        state: latest
  when: ansible_distribution in ["Ubuntu", "Debian", "Pop!_OS"]
