- name: packages | libxft | install (Archlinux)
  pacman:
    name:
      - libxft-bgra-git
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: packages | libxft | install required dep (Debian)
  apt:
    name: 
      - libxft2
      # - autoconf
      # - xutils-dev
    state: latest
  when: ansible_os_family == "Debian"

# - name: packages | clone libxft patched version (Debian)
#   git:
#     repo: https://github.com/uditkarode/libxft-bgra
#     dest: ~/src/libxft-bgra 
#   when: ansible_os_family == "Debian"
