- name: packages | gitflow
  block:
    - name: packages | gitflow | install (Archlinux)
      become_user: "{{ user }}"
      shell: "yes |  {{ aur_helper_name }} -S --removemake gitflow-avh"
      when: ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: packages | gitflow | install (Debian)
      become: true
      package:
        name: git-flow
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian", "Pop!_OS"]
