- name: packages | gitflow
  become: true
  block:
    - name: packages | gitflow | check if already installed
      stat:
        path: /usr/bin/git-flow
      register: helper_is_present

    - name: packages | gitflow | install (Archlinux)
      become_user: "{{ user }}"
      shell: "yes |  {{ aur_helper_name }} -S --removemake --noconfirm gitflow-cjs"
      when: (not helper_is_present.stat.exists) and ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: packages | gitflow | install (Debian)
      package:
        name: git-flow
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian", "Pop!_OS"]
