---
- name: packages | twingate
  block:
    - name: packages | twingate | install package (Archlinux)
      become_user: "{{ user }}"
      shell: yay -S --noconfirm --removemake twingate-client
      when: ansible_distribution in ["Archlinux", "Artix Linux"]

    - name: packages | twingate | debian
      become: true
      block:
        - name: packages | twingate | add repo to sources list
          apt_repository:
            repo: deb [trusted=yes] https://packages.twingate.com/apt/ /
            state: present
            filename: twingate

        - name: packages | twingate | install package
          package:
            name: twingate
            update_cache: yes
      when: ansible_os_family == "Debian"
  when: ansible_form_factor is defined and ansible_form_factor == "Notebook"
