- name: packages | dmenu | clone repo 
  git:
    repo: https://github.com/dixiedream/dmenu
    dest: /tmp/dmenu

- name: packages | dmenu | install dmenu 
  make:
    target: install
    chdir: /tmp/dmenu
