- name: packages | neovim | install package (Arch and debian)
  become: true
  package:
    name: neovim
    state: latest
  when: ansible_distribution in ["Archlinux", "Artix Linux", "Debian"]

- name: packages | neovim | install package (ubuntu)
  become: true
  apt:
    deb: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
