- name: packages | st | clone repo
  become: true
  git:
    repo: https://github.com/dixiedream/st
    dest: /tmp/st
    force: yes

- name: packages | st | install st
  become: true
  make:
    target: install
    chdir: /tmp/st
