---
- name: packages | Gitflow
  become: true
  block:
    - name: packages | gitflow | Archlinux
      when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"]

      block:
        - name: packages | gitflow | check if already installed
          ansible.builtin.stat:
            path: /usr/bin/git-flow
          register: pkg_is_present

        - name: packages | gitflow | install (Archlinux)
          ansible.builtin.import_tasks: _install_aur_with_helper.yml
          vars:
            aur_package_name: gitflow-cjs
            aur_creates: /usr/bin/git-flow
          when: not pkg_is_present.stat.exists
    - name: packages | gitflow | install (Debian)
      ansible.builtin.package:
        name: git-flow
        state: latest
      when: ansible_facts["distribution"] in ["Ubuntu", "Debian", "Pop!_OS"]
