- name: packages | install AUR packages (Arch linux)
  pacman:
    name:
      - auto-cpufreq
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: packages | clone auto-cpufreq repo (Debian)
  git:
    repo: https://github.com/AdnanHodzic/auto-cpufreq.git
    dest: ~/src/auto-cpufreq
  when: ansible_distribution in ["Debian", "Ubuntu"]

# - name: packages | install auto-cpufreq (Debian)
#   shell: ./auto-cpufreq-installer --install
#   args:
#     chdir: ~/src/auto-cpufreq
#   creates: /usr/local/bin/auto-cpufreq
#   when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | start and enable auto-cpufreq (Debian)
  command: auto-cpufreq --install
  register: installoutput
  changed_when: "'auto-cpufreq is running in daemon mode' not in installoutput.stdout"
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | check auto-cpufreq is started and enabled
  service: 
    name: auto-cpufreq
    state: started
    enabled: yes
