- name: packages | install Brave (Arch linux)
  pacman:
    name:
      - brave-bin
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
  when: ansible_distribution == "Archlinux"

- name: packages | install Brave required dependencies (Debian)
  package:
    name:
      - apt-transport-https
      - curl
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | setup Brave keyring (Debian)
  get_url: 
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | setup Brave repo (Debian)
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    filename: brave-browser-release
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: packages | install Brave (Debian)
  apt:
    name: brave-browser
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]
