---
- name: packages | neovim | install package
  become: true
  ansible.builtin.package:
    name: neovim
    state: latest
  when: ansible_distribution in ["Archlinux", "Artix Linux"]

- name: packages | Neovim (Debian)
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian", "Pop!_OS"]
  block:
    - name: packages | neovim (Debian) | add "unstable" repository
      ansible.builtin.apt_repository:
        repo: "ppa:neovim-ppa/unstable"
        state: present

    - name: packages | neovim (Debian) | update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: packages | neovim (Debian) | install
      ansible.builtin.apt:
        name: neovim
        state: latest
