---
- name: packages | Install drivers
  when: ansible_facts["distribution"] in ["Archlinux", "Artix Linux"] and ansible_product_version == "ThinkPad X230"
  block:
    - name: packages | install drivers | check if already installed
      ansible.builtin.stat:
        path: /usr/bin/bcmfw
      register: pkg_is_present

    - name: packages | install drivers | X230 Bluetooth firmware
      ansible.builtin.import_tasks: _install_aur_with_helper.yml
      vars:
        aur_package_name: bcm20702a1-firmware
        aur_creates: /usr/bin/bcmfw
      when: not pkg_is_present.stat.exists
