- name: system setup | apt
  become: true
  block:
    - name: system setup | apt | disable recommended and suggested package installation (Debian)
      copy:
        src: system_setup/apt.conf
        dest: /etc/apt/apt.conf.d/99norec
        owner: root
        group: root
  when: ansible_distribution == "Debian"
