---
- name: system setup | Bluetooth
  become: true
  when: ansible_distribution == "Debian"
  block:
    - name: system setup | bluetooth | create wireplumber folder
      ansible.builtin.file:
        path: /etc/wireplumber/policy.lua.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: system setup | bluetooth | copy headphones audio quality and mic conf
      ansible.builtin.copy:
        src: system_setup/bluetooth_policy.lua
        dest: /etc/wireplumber/policy.lua.d/11-bluetooth-policy.lua
        owner: root
        group: root
        mode: "0755"
