- name: system setup | debian systemctl shortcuts
  become: true
  block:
    - name: system setup | debian systemctl shortcuts | create poweroff shortcut (Debian)
      file:
        src: systemctl
        dest: /usr/bin/poweroff
        state: link
        owner: root
        group: root

    - name: system setup | debian systemctl shortcuts | create reboot shortcut (Debian)
      become: true
      file:
        src: systemctl
        dest: /usr/bin/reboot
        state: link
        owner: root
        group: root
  when: ansible_distribution == "Debian"
