- name: system setup | locale | set time zone (Archlinux)
  become: true
  file:
    src: /usr/share/zoneinfo/Europe/Rome
    dest: /etc/localtime
    state: link
    force: true
    owner: root
    group: root
    mode: 0700
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | set ntp true (Archlinux)
  become: true
  command: timedatectl set-ntp true
  changed_when: false
  ignore_errors: true
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | sync hardware clock and system clock (Archlinux)
  become: true
  command: hwclock --systohc
  changed_when: false
  ignore_errors: true
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | refresh tzdata (Archlinux)
  pacman:
    name: tzdata
    state: latest
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | set locale.gen file (Archlinux)
  become: true
  shell: echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | generate locale (Archlinux)
  command: locale-gen
  changed_when: false
  ignore_errors: true
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | create locale.conf (Archlinux)
  copy:
    src: system_setup/locale_locale.conf
    dest: /etc/locale.conf
    group: root
    owner: root
    mode: 0644
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | create vconsole.conf (Archlinux)
  copy:
    src: system_setup/locale_vconsole.conf
    dest: /etc/vconsole.conf
    group: root
    owner: root
    mode: 0644
  when: ansible_os_family == "Archlinux"

- name: system setup | locale | set caps lock as ctrl
  become_user: ale
  command: localectl --no-convert set-x11-keymap it '' '' ctrl:nocaps
  ignore_errors: yes
