- name: system setup | locale
  become: true
  block:
    - name: system setup | locale | set time zone (Archlinux)
      file:
        src: /usr/share/zoneinfo/Europe/Rome
        dest: /etc/localtime
        state: link
        force: true
        owner: root
        group: root
        mode: 0700

    - name: system setup | locale | set ntp (Archlinux)
      command: timedatectl set-ntp true
      changed_when: false
      ignore_errors: true
      when: readlink.stdout.find('systemd') != -1

    # - name: system setup | locale | set ntp (Artix)
    #   runit:
    #     name: ntpd
    #     state: started
    #     enabled: true
    #   when: readlink.stdout.find('runit') != -1

    - name: system setup | locale | sync hardware clock and system clock (Archlinux)
      command: hwclock --systohc
      changed_when: false
      ignore_errors: true

    - name: system setup | locale | refresh tzdata (Archlinux)
      command: pacman -S --noconfirm tzdata
      changed_when: false
      ignore_errors: true

    - name: system setup | locale | set locale.gen file (Archlinux)
      shell: echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen

    - name: system setup | locale | generate locale (Archlinux)
      command: locale-gen
      changed_when: false
      ignore_errors: true

    - name: system setup | locale | create locale.conf (Archlinux)
      copy:
        src: system_setup/locale_locale.conf
        dest: /etc/locale.conf
        group: root
        owner: root
        mode: 0644

    - name: system setup | locale | create vconsole.conf (Archlinux)
      copy:
        src: system_setup/locale_vconsole.conf
        dest: /etc/vconsole.conf
        group: root
        owner: root
        mode: 0644
  when: ansible_os_family in ["Archlinux", "Artix Linux"]
