- name: system setup | lock screen on suspend | copy conf file
  copy:
    src: system_setup/lock_on_suspend.conf
    dest: /etc/systemd/system/slock@.service
    owner: root
    group: root

- name: system setup | lock screen on suspend | enable service
  become: true
  service:
    name: "slock@ale.service"
    enabled: yes
