- name: system setup | microcode | install package for amd
  become: true
  package:
    name: "{{ amd_microcode_package }}"
    state: latest
  when:
    - microcode_amd_install is defined
    - microcode_amd_install == true

- name: system setup | microcode | install package for intel
  become: true
  package:
    name: "{{ intel_microcode_package }}"
    state: latest
  when:
    - microcode_intel_install is defined
    - microcode_intel_install == true
