- name: system setup | remove beep | remove pcspkr
  shell: rmmod pcspkr 2>/dev/null

- name: system setup | remove beep | blacklist pcspkr
  shell: echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
