---
- name: system setup | remove beep | remove pcspkr
  become: true
  when: ansible_distribution in ["Archlinux", "Artix Linux", "Debian"]
  block:
    - name: system setup | remove beep | remove pcspkr
      ansible.builtin.command: rmmod pcspkr
      ignore_errors: true

    - name: system setup | remove beep | check if already blacklisted
      ansible.builtin.stat:
        path: /etc/modprobe.d/nobeep.conf
      register: nobeep_check

    - name: system setup | remove beep | blacklist pcspkr
      ansible.builtin.shell: echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
      when: not nobeep_check.stat.exists
