- name: system setup | remove beep | remove pcspkr
  command: rmmod pcspkr 2>/dev/null

- name: system setup | remove beep | blacklist pcspkr
  command: echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
